### ISSUE TITLE
Having troubles sending Testfligh builds

### ISSUE THREAD

**Issue by txaiwieser** [alexaubry/alternate-icons#4]
Hey, first thank you for sharing this script with us. Its great! 👏 

I'm having problems with the latest Xcode 9 build (beta6). When trying to send builds to testflight it gives me this errors:

```
[10:17:14]: Transporter transfer failed.

[10:17:14]: description length:8180571

ERROR ITMS-90713: "Missing Info.plist value. A value for the Info.plist key CFBundleIconName is missing in the bundle 'XXXXXX'. Apps that provide icons in the asset catalog must also provide this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7."



[10:17:14]: description length:8180571

ERROR ITMS-90713: "Missing Info.plist value. A value for the Info.plist key CFBundleIconName is missing in the bundle 'XXXXXX'. Apps that provide icons in the asset catalog must also provide this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7."

ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0."

\nERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0."

The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

```

If you have any info about this i can help submit a PR fixing this issue, just need some guidance :)

Thanks 👍

**Comment by alexaubry** [comment]
Hey! 👋 

Xcode 9 introduced a new procedure for embedding alternate icons to fix an issue with iTunes Connect. It is described here: https://twitter.com/jamesthomson/status/903250089518526464.

I'm currently working on a fix, thanks for reporting 😃

**Comment by alexaubry** [comment]
@txaiwieser I just opened PR #5 that updates the script for Xcode 9. Could you please tell me if it fixes your issue?

**Comment by txaiwieser** [comment]
I seems to be working fine now. The only drawback is to have the main AppIcon and the alternate ones separated in different .xcassets

Here we have a couple .xcassets, one for icons, one for images, and .. on for icons, and now we need to have two.


I just wish Apple would just accept alternate icons from .xcassets 🙄 

Thanks! Will keep using your script. Its an awesome helper! :D

**Comment by alexaubry** [comment]
Version [2.0.0](https://github.com/alexaubry/alternate-icons/releases/tag/2.0.0) just shipped with a fix for this issue.

Thank you for helping resolving it and for using the script! 👍

I agree that the current requirements are not the best. We'll see if they improve the process in future Xcode versions... 🤞
