### ISSUE TITLE
Can't compile library

### ISSUE THREAD

**Issue by MaxHasADHD** [alexaubry/alternate-icons#8]
Following the instructions, the project does not compile properly anymore. Looks like it can't reach the Files dependency for me at least. Running Mojave and Xcode 10

**Comment by RSady** [comment]
I'm having the same issue.  I've been fighting with this for almost an hour now.  I'm getting the error:

`
The operation couldn't be completed. (Files.FileSystem.Item.PathError error 0.)
Command PhaseScriptExecution failed with a nonzero exit code
`

Any help?
